### PR TITLE
#237 Asset Type List to Count

### LINKED ISSUE #237: (E1) UI Enhancements - Asset Type Thresholds
As a user, I want a cleaner and more user-friendly UI interface.

This issue aims at refactoring and enhancing some of the functionalities provided by our UI.

Acceptance Criteria:
- [ ] On the Asset Type List Screen, display the number of assets in each threshold category instead of the value of the threshold itself

### PR DESCRIPTION
**Pull request by PaulMicu**
Now the Asset Type list will display the amount of each asset in the specific threshold instead of the value of the threshold 

resolves #237

### CODE REVIEW

**Review by TalalBazerbachi — APPROVED** [review]
it looks much better having the number of assets for each threshold instead of the value of each threshold.

**Comment by najimgh** [comment]
Please fix the merge conflicts.

Other than that, it makes much more sense to have the number of assets for each threshold.

**Review by najimgh — CHANGES_REQUESTED** [review]
Please fix the merge conflicts.

Other than that, it makes much more sense to have the number of assets for each threshold.

**Review by JayChouteau — APPROVED** [review]
Nice quality of life change for UI/UX purposes. Code is clean and the display is more meaningful for the user's needs and intentions. Once the merging conflicts have been resolved, this can be merged.

**Comment by t98b** [comment]
There are no merge conflicts with develop I think we can merge

**Review by najimgh — APPROVED** [review]

**Pull request merged**
