### PR TITLE
[BUG Fixed] F12 - Model/Asset type association logic fixed

### LINKED ISSUE #292: [BUG] F12 - Model/Asset Type Association's logic has been broken
**Describe the bug**
When trying to save a model association for a specific asset type, the association doesn't get saved properly. The feature doesn't work anymore.

**To Reproduce**
1. Go to asset type list
2. Click on any asset type in the list
3. Click on the model tab
4. Select a model that is not currently selected (borders aren't red)
5. Click on Save
6. Click back on the same asset type from the list
7. On the information tab, read the associated RUL model text box -> see error
8. On the model tab, check which thumbnail has red borders -> see error

**Expected behavior**
The selection should be properly saved to be displayed in the UI

**Screenshots**

**Desktop (please complete the following information):**
 - OS: any OS

**Additional context**
The previous logic of saving an association between the model and the asset type was based on the fact that the trained_model table in the database would only hold 1 trained model per asset type. This meant that selecting a model and saving the selection would change the model ID in the trained model table for the asset type in the database and change the retrain tag to true. However, since issues #222, #276, and #270, the trained_model table holds multiple model entries for 1 asset type.  Since then, another attribute was added to the table to keep track of which entries are meant for evaluation and which entries are meant for the application (status_id). Most likely, the logic of the association will have to be updated to take into consideration these new changes.

TL:DR -> The logic has been broken and needs to be fixed.

### PR DESCRIPTION
**Pull request by JayChouteau**
This pull-request regards the fixing of the bug related to F12. For a full description of the bug, as well as the observations and resolution, please refer to the issue: I added screenshots and explanations. To test the functionality, please refer to the bug issue as well as the issue (#218 ) for the desired behavior.

### CODE REVIEW

**Review by TalalBazerbachi — CHANGES_REQUESTED** [review]
I get an error when I try to access the models page.
image

**Comment by JayChouteau** [comment]
@t98b Did you run the latest script? V18? Normally it should work.

**Review by TalalBazerbachi — APPROVED** [review]
After running script V18 the application didn't cause any errors, and model selection is now working as intended

**Review by jeffbuonamici — APPROVED** [review]
Bug has been fixed. Good job.

**Pull request merged**
