### PR TITLE
SonarQube Sprint 8 refactoring

### LINKED ISSUE #228: [Refactoring] SonarQube Analysis report and refactoring - S8
As a developer, I would like to have clean code.

Acceptance Criteria:
- [x] Document and print the SonarQube Analysis run on Sprint 8
- [x] Refactor the found issues:
- [x]  Bug tolerance: 1
- [x]  Security tolerance: 1
- [x]  Code smell tolerance: 10
- [x]  Code dupplication tolerance: 3-4%

### PR DESCRIPTION
**Pull request by JayChouteau**
This pull request deals with all the SonarQube analysis issues found in the code at the end of Sprint 8.It also includes a little bit of code clean-up as well as an updated dump file. Here are the key points to look for:
1) Dump file v18
Please wipe your current database schema and run v18. There were some errors introduced in v17. 
2) Extract Methods
Added clarity and comprehensiveness to the assetTypeInfoController
3) Make the default field attributes of the different RUL model implementation files to static members. This is to reduce object creation

### CODE REVIEW

**Comment by JayChouteau** [comment]
This is what the schema of the database should look like at this point in the project:
image

**Review by PaulMicu — APPROVED** [review]

**Review by Khal-Shah — APPROVED** [review]
Approved

**Review by rdsaliba — APPROVED** [review]
Just ran your branch. Everything seems fine. Also ran the sonarqube report and it looks good! 
image

**Comment by rdsaliba** [comment]
The security hotspot is only related to a a sql injection which we're not dealing with since its safe.

**Pull request merged**
