### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by jeffbuonamici**
Added UI from the following issues:

#36 Add Sidebar Menu
#37 System information view
#38 System Dashboard
#39 Add System

### CODE REVIEW

**Review by PaulMicu — CHANGES_REQUESTED** [review]
it looks like there's a missing dependency in the pom.xml, can you check it out. Thanks

**Review by PaulMicu — CHANGES_REQUESTED** [review]
Is it possible to remove or hide the scrolling bar on the Systems.fxml and the SystemInfo.fxml Page. And to allow scrolling by swiping up and down as it would be on a touch screen

**Comment by jeffbuonamici** [comment]
> Is it possible to remove or hide the scrolling bar on the Systems.fxml and the SystemInfo.fxml Page. And to allow scrolling by swiping up and down as it would be on a touch screen

Good point. I will look into that.

**Comment by rdsaliba** [comment]
This pull request will be merged. A new issue (#68)  has been opened to address the concerns.

**Pull request merged**
