### PR TITLE
66 68 ui

### LINKED ISSUE #66: Display System Dashboard Details (List View)
As a user, I want to visualize the systems in a list view so that it's easier to navigate through the assets.

This user story will be realized by creating a second view of the system dashboard. A list view of all the systems with their details will be created as the second view of the system dashboard. The first view of the system dashboard is the more general grid view.

Acceptance Criteria:
- [x] Display a list of all systems as the "System Dashboard Details" View
- [x] Display System Type
- [x] Display Serial Number
- [x] Display RUL Value
- [ ] Display RUL Model
- [ ] Display System Recommendation

### LINKED ISSUE #68: Remove Scroll bar and add touch capable scrolling
As a user, I want to scroll using touch gesture so that a user could use his finger to scroll up and down.

Acceptance criteria:
- [x] Remove scroll bars from all pages
- [x] Allow scrolling by dragging the screen, as it would be on a tablet

### PR DESCRIPTION
**Pull request by jeffbuonamici**
- Did some refactoring to solve the code duplication issues.
- Added a list view of all the assets
- Removed scrolls bars

About touch screen capabilities:
I'm not able to test with a physical touch screen. I have a feeling there's going to be a bug when scrolling. That when you put your finger down to scroll, it'll register as a "click" on some of the screen elements.

### CODE REVIEW

**Comment by jeffbuonamici** [comment]
I'm going to fix these conflicts.

**Comment by jeffbuonamici** [comment]
Please don't needlessly "Auto Reformat" the fxml files. It creates huge blocks of conflicts. Plus Windows and Mac format the files differently anyway due to their spacing differences.

**Review by JayChouteau — COMMENTED** [review]
Good work Jeff. Sadly, I am not able to test the touch screen as I don't have the tools to do so. It would be important to find someone who can do it as we need to test the feature. Both the removal of code duplication as well as the list view are well done. The addition of tabs to switch between views between the thumbnails and list view is a very good idea and I think it looks intuitive in terms of UI.

The only comment I would make that might require a change in this issue or a maybe a future issue would be to make it more indicative of which tab you are on and viewing. I am referencing to a slight different shade/color between the viewed tab and the other ones as well as the tab title coming to the front when selected. Example: any web browser, or the following [link](https://kyusuf.com/post/completely-css-tabs/) (just look at the image). 

Overall very good job Jeff.

**Review by JayChouteau — APPROVED** [review]
I looked up the acceptance criteria for these 2 issues and it seems like it passes them, except for two that will have to be done in a future sprint:
- Scrolling: we will get a tablet for the next sprint to test it out
- Displaying recommendation in the list view: The recommendation feature hasn't been done yet, so this acceptance criteria doesn't apply anymore

**Pull request merged**
