### PR TITLE
Refactoring all issues from SonarQube

### LINKED ISSUE #227: [Refactoring] SonarQUbe Analysis report and refactoring - S7
As a developer, I would like to have clean code.

Acceptance Criteria:
- [x] Document and print the SonarQube Analysis run on Sprint 7
- [x] Refactor the found issues:
- [x]  Bug tolerance: 1
- [x]  Security tolerance: 1
- [x]  Code smell tolerance: 10
- [x]  Code dupplication tolerance: 3-4%

### PR DESCRIPTION
**Pull request by rdsaliba**
Could you confirm? On our side:

LSTMTEST could be run
Server could be run
Ui could be run
Real-Time Demo could be run
SonarQube issues introduced with Najim PR were fixed
The local maven repo and the pom file is back to how it was

### CODE REVIEW

**Comment by rdsaliba** [comment]
image

**Review by JayChouteau — APPROVED** [review]
For all comments and reviews, please refer to the previous SonarQube pull-request. Approved.

**Review by TalalBazerbachi — CHANGES_REQUESTED** [review]
UI is working as intended.
but I get this error when I run the Server.
image

**Comment by rdsaliba** [comment]
@t98b Everything runs fine for me.

**Review by TalalBazerbachi — APPROVED** [review]
The problem seems to have been caused by my database configuration, I ran V15 again and server was working properly.
nice work roy!

**Pull request merged**
