### PR TITLE
28 30 data cleaning enhancements

### PR DESCRIPTION
**Pull request by Khal-Shah**
#28 
#69 

The original method of applying the AttributeSelection filter from the Weka Library to clean the data potentially removes attributes that can hold significant information that we might want to keep (Ex: Sensor 9, 14).

This additional method ensures _only_ the attributes that have no fluctuation at all (standard deviation = 0) are removed to produce a minimally reduced dataset. Unlike the first method, this doesn't check for any correlation with the RUL, but rather the values of the attribute themselves (if a column has no fluctuation, attribute corresponding to that column is removed). 

Either of these methods can be used to clean the data and then observe which one creates a more accurate model. 

Refactoring: deletes "train_FD001_filtered.arff" file that did not have correct data.

### CODE REVIEW

**Review by PaulMicu — CHANGES_REQUESTED** [review]
can you please change the name of the function to something more descriptive, thanks

**Comment by Khal-Shah** [comment]
> can you please change the name of the function to something more descriptive, thanks

Do you mean the process function? 
I named it process2 since the first one there was just called process. 

Should I rename both or just process2()?

**Comment by PaulMicu** [comment]
if there was only one function process would be fine but since we have two that do a similar thing i think we should call it processFullReduction and processMinimalReduction . Or something like that

**Comment by Khal-Shah** [comment]
> if there was only one function process would be fine but since we have two that do a similar thing i think we should call it processFullReduction and processMinimalReduction . Or something like that

Agreed.

Refactoring activity:
Data cleaning method names have been changed:
process() -> processFullReduction()
process2() -> processMinimalReduction()

**Review by PaulMicu — COMMENTED** [review]
thank you for the correction

**Review by PaulMicu — APPROVED** [review]

**Pull request merged**
