### PR TITLE
194 unit testing

### LINKED ISSUE #162: System Testing - Assets
This system testing batch targets the user stories concerning the displaying, consulting, or editing of the assets. A batch means that different system test scenarios need to be developed for the asset-related user stories.

Acceptance Criteria:
- [ ] Documentation on Confluence for the system test sections, cases and scenarios

Develop functioning system tests scenarios and implementing them (automated end-to-end tests) for the following user stories/issues:
- [ ] Display asset information (thumbnails)
- [ ] Display asset information (list view)
- [ ] Scroll through the thumbnails view
- [ ] Scroll through the list view
- [ ] Add Asset
- [ ] Remove Asset

The system tests are implemented using the testfx framework set up in the e2e folder.

### LINKED ISSUE #194: Unit testing - Raising up the coverage
This issue is meant to raise the code coverage of our project. Clover is the tool being used to assess code coverage and unit testing.

Acceptance Criteria:
- [ ] 70% of code coverage with unit tests

To run Clover, please check the following documentation:
https://notorious-eng.atlassian.net/wiki/spaces/DOCUMENTAT/pages/295141377/Unit+testing

### PR DESCRIPTION
**Pull request by jeffbuonamici**
Unit and System testing.

This resolves #194 and #162

Refer to their issues for coverage reports:
https://app.zenhub.com/workspaces/notorious-eng-5f5b91b10156a900162c5640/issues/rdsaliba/notorious-eng/194

https://app.zenhub.com/workspaces/notorious-eng-5f5b91b10156a900162c5640/issues/rdsaliba/notorious-eng/162

### CODE REVIEW

**Comment by jeffbuonamici** [comment]
Just letting the reviewers know that there was a merge conflict when the pull request was made.

image

I removed the top GET_ASSET_TYPE_ID_COUNT. Hopefully that was the correct call.

**Comment by rdsaliba** [comment]
Hey Jeff! That's a hell lot of unit tests my friend. I have tried your branch on my side and everything seems fine. They all pass. For next time, it would be best to have more descriptive commits and to also reference the task for which it means to add unit tests (#162). It would facilitate the review. Other than that.. thumbs up!

**Review by rdsaliba — APPROVED** [review]

**Comment by jeffbuonamici** [comment]
Yeah I thought all testing was under the #194 issue, I didn't see #162.

**Review by JayChouteau — APPROVED** [review]
As discussed previously, the pull request will be merged due to time constraints on the release, but the testing files will need some structuring and refactoring afterwards, and that refactoring/re-structuring will need to happen before any other testing effort is made in the project. That is why there won't be any comments directly on code snippets for this pull request.

When it comes to this pull request, the units tests are working properly and the coverage is good. When it comes down to the system testing, the tests are all mixed up inside unit testing files and are not covering full features. We will come back to this in the next sprint.

**Pull request merged**
