### PR TITLE
#222 parametrize models

### LINKED ISSUE #222: Add Parameters to all models
As a developer, I want to find and add all Parameters for different models, to allow users to modify model settings.
Description:
Research all the parameters required for all models. Update the current implementation of all to add all the parameters. Parameter values will either be retrieved from the database or it will be requested by the UI.

Acceptance Criteria:
- [x] Find Different Parameters for all 8 models.
<s>- [ ] Add Parameters to the Database.</s>
- [x] Update the implementation for all models to add new parameters.

### PR DESCRIPTION
**Pull request by Khal-Shah**
All of the ModelImpl classes now have parameters that can be applied to the models. Resolves #222.
~~Also includes unit tests for 6 of the 8 models (for updating parameters), as this was getting quite long, I will add the other two if this PR stays open for a while.~~ Unit tests added for all models.

Note: Me and @PaulMicu had a Code-Together session where he setup all of the architecture and got this issue kickstarted, his contributions are not shown in the commits because I was the host of the session.

### CODE REVIEW

**Review by TalalBazerbachi — CHANGES_REQUESTED** [review]
Nice work Khalid!
I have compared the parameters with the documentation on Confluence, all of them have been added.
However, when I try to run the Server I get an error.
image

**Comment by jeffbuonamici** [comment]
> Nice work Khalid!
> I have compared the parameters with the documentation on Confluence, all of them have been added.
> However, when I try to run the Server I get an error.
> image

I get this error as well. I believe this started happening when #278 got pushed to develop.

**Comment by Khal-Shah** [comment]
Can you guys re-run the V15 dump file? I do not get this error running V15.

**Comment by jeffbuonamici** [comment]
> Can you guys re-run the V15 dump file? I do not get this error running V15.

I've rerun the script multiple times

**Review by najimgh — CHANGES_REQUESTED** [review]
Screen Shot 2021-03-13 at 4 27 43 PM

I am getting a slightly different error when running the Server

**Review by TalalBazerbachi — APPROVED** [review]
I am not getting the error anymore

**Comment by Shirwarsame** [comment]
Server runs fine.
Error when running CMBSApplication
faultimage

**Comment by Khal-Shah** [comment]
> Server runs fine.
> Error when running CMBSApplication
> faultimage

Can you check the Utilities package in UI and make sure "package Utilities" have the correct spelling
image

And match it with the CBMSApp class
image

**Comment by Shirwarsame** [comment]
> > Server runs fine.
> > Error when running CMBSApplication
> > faultimage
> 
> Can you check the Utilities package in UI and make sure "package Utilities" have the correct spelling
> image
> 
> And match it with the CBMSApp class
> image

Issue solved

**Review by Shirwarsame — APPROVED** [review]

**Review by najimgh — APPROVED** [review]
Not getting errors anymore

**Pull request merged**
