### PR TITLE
#43 toggle model archived

### LINKED ISSUE #43: (F6 modified) Toggle RUL Model
As a developer, I want to be able to toggle an RUL model off or on easily in the code.

Acceptance Criteria:
- [x] Add the archived indicator in the model table (in the database)
- [x] Go in the code and add the archived check the to the queries so that you're only retrieving non-archived models.
- [x] Unit Tests
- [x] Code convention (warnings in IDE, code cleanup)

### PR DESCRIPTION
**Pull request by Shirwarsame**
Allows the developer to select which models are used in the project

To test the branch:
1.Run the cmbs_scriptV17
2.To remove which models are displayed change the archived value of the model to 1

resolves #43

### CODE REVIEW

**Review by jeffbuonamici — CHANGES_REQUESTED** [review]
This meets the acceptance criteria, but can you create a dump file for script 16 and zip the folder

**Review by JayChouteau — CHANGES_REQUESTED** [review]
This completes the acceptance criteria. However, as @jeffbuonamici mentioned, could you please make a dumpfile for the new changes you added on top of dumpfile v15 (latest one)?

**Review by najimgh — DISMISSED** [review]
Simply need to make sure you add your new changes on top of Dump file 15

**Review by rdsaliba — DISMISSED** [review]
Great. De qua mox supra. Thanks

**Comment by Khal-Shah** [comment]
As has been said, this does resolve the toggle issue. You should corroborate with @t98b (currently working on a V16) to integrate both of your changes into the next dump file or else your changes might become obsolete (or vice vice versa) with the next dump file that gets pushed.

**Review by PaulMicu — DISMISSED** [review]
You also need to add the archived check in all the queries of trained model to check if the trained model is archived based of the column in the model table

**Review by JayChouteau — APPROVED** [review]

**Review by jeffbuonamici — APPROVED** [review]

**Pull request merged**
